import type { ReactNode } from 'react'
import { Activity, Gauge, MessageSquareText, ShieldCheck, Target, Users, Waves } from 'lucide-react'
import type { Analytics, Item, LearningQuality, Lesson, SampleMetric, Skill } from '../types'
import { DataTable, Metric, Page, StatePanel } from '../ui'
import { useQuery } from '../query'

const QualityStatus = ({ status }: { status: string }): ReactNode => <span className={`badge ${status === 'sufficient' ? 'live' : status === 'insufficient_sample' ? 'warning' : ''}`}>{status === 'insufficient_sample' ? 'Chưa đủ mẫu' : status === 'sufficient' ? 'Đủ mẫu' : status}</span>
const QualityTable = ({ title, rows, label }: { title: string; rows: SampleMetric[]; label: (key: string) => string }): ReactNode => <section className="card"><div className="section-heading"><div><h2>{title}</h2><p>Chỉ hiển thị độ chính xác khi đủ cỡ mẫu.</p></div></div><DataTable empty={!rows.length}><thead><tr><th>Nhóm</th><th>Số mẫu</th><th>Trạng thái</th><th>Độ chính xác</th></tr></thead><tbody>{rows.map((row) => <tr key={row.key}><td>{label(row.key)}</td><td>{row.samples}</td><td><QualityStatus status={row.status} /></td><td>{row.correctness === null ? <span className="muted">Chưa đủ dữ liệu</span> : <span className={`badge ${row.correctness >= .7 ? 'live' : 'warning'}`}>{Math.round(row.correctness * 100)}%</span>}</td></tr>)}</tbody></DataTable></section>
const QualityBars = ({ rows }: { rows: SampleMetric[] }): ReactNode => <div className="analytics-bars">{rows.map((row) => { const value = row.correctness === null ? 0 : Math.round(row.correctness * 100); return <div className="analytics-bar" key={row.key}><div className="bar-meta"><strong>{row.key}</strong><span>{row.correctness === null ? 'Chưa đủ mẫu' : `${value}%`}</span></div><div className="bar-track" role="img" aria-label={`${row.key}: ${row.correctness === null ? 'chưa đủ mẫu' : `${value}% chính xác`}`}><span style={{ width:`${value}%` }} /></div><small>{row.samples} mẫu</small></div> })}</div>

export function AnalyticsPanel(): ReactNode {
  const overview = useQuery<Analytics>('/admin/analytics/overview'); const quality = useQuery<LearningQuality>('/admin/analytics/learning-quality'); const skills = useQuery<Skill[]>('/admin/skills'); const items = useQuery<Item[]>('/admin/items'); const lessons = useQuery<Lesson[]>('/admin/lessons')
  const skillLabel = (key: string): string => skills.data?.find((row) => String(row.id) === key)?.nameVi ?? key
  const itemLabel = (key: string): string => { const row = items.data?.find((item) => item.id === key); return row?.stableId || row?.stem || key }
  const lessonLabel = (key: string): string => lessons.data?.find((lesson) => lesson.id === key)?.titleVi ?? key
  return <Page title="Analytics & Reports" description="Đánh giá hoạt động học tập và chất lượng mô hình mà không suy diễn khi thiếu mẫu." actions={quality.data && <span className="badge">Cập nhật {new Date(quality.data.generatedAt).toLocaleString('vi-VN')}</span>}><StatePanel query={overview}>{overview.data && <div className="metric-grid"><Metric label="Người học" value={overview.data.learners} icon={Users} /><Metric label="Active 30 ngày" value={overview.data.activeLearners} icon={Activity} tone="success" /><Metric label="Lượt trả lời" value={overview.data.answers} icon={MessageSquareText} tone="neutral" /><Metric label="Độ chính xác" value={`${Math.round(overview.data.correctness * 100)}%`} icon={Target} tone="warning" /></div>}</StatePanel>
    <StatePanel query={quality}>{quality.data && <>
      <div className="analytics-summary"><section className="card analytics-chart"><div className="section-heading"><div><h2>Learning quality theo CEFR</h2><p>Độ chính xác quan sát từ dữ liệu đủ mẫu.</p></div><Gauge aria-hidden="true" /></div><QualityBars rows={quality.data.byCefr} /></section><div className="quality-cards"><section className="card quality-card"><span className="quality-icon"><Target aria-hidden="true" /></span><div><h2>Calibration</h2><strong>{quality.data.calibration.samples} mẫu</strong></div><QualityStatus status={quality.data.calibration.status} /><p>Brier score: {quality.data.calibration.brierScore === null ? 'Chưa đủ dữ liệu' : quality.data.calibration.brierScore.toFixed(3)}</p></section><section className="card quality-card"><span className="quality-icon"><Waves aria-hidden="true" /></span><div><h2>Data drift</h2><strong>{quality.data.drift.recentSamples} gần đây / {quality.data.drift.baselineSamples} nền</strong></div><QualityStatus status={quality.data.drift.status} /><p>Chênh lệch: {quality.data.drift.delta === null ? 'Chưa đủ dữ liệu' : `${Math.round(quality.data.drift.delta * 100)}%`}</p></section><section className="card quality-card"><span className="quality-icon"><ShieldCheck aria-hidden="true" /></span><div><h2>Fairness</h2><strong>{quality.data.fairness.samples} mẫu</strong></div><QualityStatus status={quality.data.fairness.status} /><p>{quality.data.fairness.reason}</p></section></div></div>
      <QualityTable title="Chất lượng theo CEFR" rows={quality.data.byCefr} label={(key) => key} />
      <StatePanel query={skills}><QualityTable title="Chất lượng theo kỹ năng" rows={quality.data.bySkill} label={skillLabel} /></StatePanel>
      <StatePanel query={items}><QualityTable title="Chất lượng theo item" rows={quality.data.byItem} label={itemLabel} /></StatePanel>
      <StatePanel query={lessons}><QualityTable title="Chất lượng theo bài học" rows={quality.data.byLesson} label={lessonLabel} /></StatePanel>
    </>}</StatePanel></Page>
}
