import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { Boxes, ClipboardList, ListChecks, Plus, Search, Sparkles, TextCursorInput } from 'lucide-react'
import { api, ApiError } from '../../../lib/api'
import type { GeneratedItemsResponse, Item, Skill } from '../types'
import { CefrSelect, ConfirmDialog, DataTable, Dialog, Field, FormActions, Metric, OverflowText, Page, Pagination, StatePanel } from '../ui'
import { useQuery } from '../query'

export function ItemsPanel(): ReactNode {
  const query = useQuery<Item[]>('/admin/items'); const skills = useQuery<Skill[]>('/admin/skills'); const [editing, setEditing] = useState<Item>(); const [editorOpen, setEditorOpen] = useState(false); const [message, setMessage] = useState<string>(); const [search, setSearch] = useState(''); const [typeFilter, setTypeFilter] = useState(''); const [skillFilter, setSkillFilter] = useState(''); const [page, setPage] = useState(0); const [pageSize, setPageSize] = useState(10); const [pendingDelete, setPendingDelete] = useState<Item>(); const [deleting, setDeleting] = useState(false)
  const [generateOpen, setGenerateOpen] = useState(false); const [generating, setGenerating] = useState(false); const [generateError, setGenerateError] = useState<string>()
  const rows = query.data ?? []; const filtered = rows.filter((row) => { const keyword = search.trim().toLowerCase(); return (!keyword || `${row.stableId ?? row.id} ${row.stem} ${row.skillCode}`.toLowerCase().includes(keyword)) && (!typeFilter || row.type === typeFilter) && (!skillFilter || row.skillCode === skillFilter) }); const safePage = Math.min(page, Math.max(0, Math.ceil(filtered.length / pageSize) - 1)); const visibleRows = filtered.slice(safePage * pageSize, (safePage + 1) * pageSize)
  useEffect(() => { if (safePage !== page) setPage(safePage) }, [page, safePage])
  const closeGenerate = (): void => { if (!generating) { setGenerateOpen(false); setGenerateError(undefined) } }
  const openCreate = (): void => { setEditing(undefined); setMessage(undefined); setEditorOpen(true) }; const openEdit = (row: Item): void => { setEditing(row); setMessage(undefined); setEditorOpen(true) }; const closeEditor = (): void => { setEditorOpen(false); setEditing(undefined) }
  const submit = async (event: FormEvent<HTMLFormElement>): Promise<void> => { event.preventDefault(); const values = new FormData(event.currentTarget); const options = String(values.get('options')).split('\n').map((x) => x.trim()).filter(Boolean); const stableId = String(values.get('stableId')).trim(); const body = { stableId:stableId || null, skillId:Number(values.get('skillId')), cefrLevel:String(values.get('cefrLevel')), type:String(values.get('type')), stem:String(values.get('stem')), options, correctAnswer:String(values.get('correctAnswer')), explanationVi:String(values.get('explanationVi')), source:String(values.get('source')), license:editing ? editing.license : 'Proprietary', reviewer:editing ? editing.reviewer : 'Admin CMS', contentVersion:editing ? editing.contentVersion : 'admin-v1', a:editing ? editing.a : 1, b:editing ? editing.b : 0, c:editing ? editing.c : (options.length ? 1/options.length : 0), audioUrl:editing ? editing.audioUrl : null }; try { await api(editing ? `/admin/items/${editing.id}` : '/admin/items', { method:editing ? 'PUT' : 'POST', body:JSON.stringify(body) }); closeEditor(); setMessage('Đã lưu item.'); await query.reload() } catch (reason) { setMessage(`Không thể lưu: ${reason instanceof ApiError ? reason.code : 'unexpected_error'}`) } }
  const remove = async (): Promise<void> => { if (!pendingDelete) return; setDeleting(true); try { await api(`/admin/items/${pendingDelete.id}`, { method:'DELETE' }); setPendingDelete(undefined); setMessage('Đã xóa item.'); await query.reload() } catch (reason) { setMessage(`Không thể xóa: ${reason instanceof ApiError ? reason.code : 'unexpected_error'}`); setPendingDelete(undefined) } finally { setDeleting(false) } }
  const generate = async (event: FormEvent<HTMLFormElement>): Promise<void> => { event.preventDefault(); if (generating) return; const values = new FormData(event.currentTarget); setGenerating(true); setGenerateError(undefined); try { const response = await api<GeneratedItemsResponse>('/admin/items/generate', { method:'POST', body:JSON.stringify({ skillCode:String(values.get('skillCode')), cefrLevel:String(values.get('cefrLevel')), type:String(values.get('type')), count:Number(values.get('count')) }) }); setGenerateOpen(false); setMessage(`Đã tạo ${response.generated} item bằng AI.`); await query.reload() } catch (reason) { if (reason instanceof ApiError) { const detail = reason.errors.length ? reason.errors.join(', ') : reason.code; setGenerateError(reason.status === 429 ? 'Đã vượt giới hạn tạo nội dung. Vui lòng thử lại sau.' : reason.status === 503 ? 'Dịch vụ AI đang tạm gián đoạn.' : `Không thể tạo item: ${detail}`) } else setGenerateError('Không thể tạo item: unexpected_error') } finally { setGenerating(false) } }
  return <Page title="Item Bank" description="Quản lý câu hỏi, đáp án và provenance trong vùng Admin được bảo vệ." actions={<><button type="button" onClick={openCreate}><Plus size={18} aria-hidden="true" /> Tạo item</button><button className="primary" type="button" onClick={() => { setGenerateError(undefined); setGenerateOpen(true) }}><Sparkles size={18} aria-hidden="true" /> Tạo bằng AI</button></>}>
    {message && <div className={`status-banner ${message.startsWith('Không thể') ? 'error' : ''}`} role="status">{message}</div>}
    <div className="metric-grid"><Metric label="Tổng items" value={rows.length} icon={ClipboardList} /><Metric label="MCQ" value={rows.filter((row) => row.type.includes('mcq')).length} icon={ListChecks} tone="success" /><Metric label="Cloze" value={rows.filter((row) => row.type === 'cloze').length} icon={TextCursorInput} tone="warning" /><Metric label="Kỹ năng phủ" value={new Set(rows.map((row) => row.skillCode)).size} icon={Boxes} tone="neutral" /></div>
    <section className="card toolbar" aria-label="Bộ lọc item"><div className="toolbar-fields"><Field label="Tìm item"><div className="search-input"><Search aria-hidden="true" /><input type="search" value={search} onChange={(event) => { setSearch(event.target.value); setPage(0) }} placeholder="Stable ID, câu hỏi hoặc skill…" /></div></Field><Field label="Loại"><select value={typeFilter} onChange={(event) => { setTypeFilter(event.target.value); setPage(0) }}><option value="">Tất cả loại</option>{[...new Set(rows.map((row) => row.type))].sort().map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Kỹ năng"><select value={skillFilter} onChange={(event) => { setSkillFilter(event.target.value); setPage(0) }}><option value="">Tất cả skill</option>{[...new Set(rows.map((row) => row.skillCode))].sort().map((value) => <option key={value}>{value}</option>)}</select></Field></div><span className="toolbar-meta">{filtered.length} / {rows.length} items</span></section>
    <StatePanel query={query}><DataTable empty={!filtered.length} stickyActions layout="items"><thead><tr><th>Stable ID</th><th>Câu hỏi</th><th>Skill</th><th>CEFR</th><th className="table-pin-secondary">Loại</th><th>Thao tác</th></tr></thead><tbody>{visibleRows.map((row) => <tr key={row.id}><td><OverflowText text={row.stableId ?? row.id} tone="code" /></td><td className="wide"><OverflowText text={row.stem} lines={2} tone="primary" /><OverflowText text={`Nguồn: ${row.source}`} lines={2} tone="secondary" /></td><td><OverflowText text={row.skillCode} /></td><td><span className="badge warning">{row.cefrLevel}</span></td><td className="table-pin-secondary"><span className="badge">{row.type}</span></td><td><div className="table-actions"><button type="button" onClick={() => openEdit(row)}>Sửa</button><button className="danger" type="button" onClick={() => setPendingDelete(row)}>Xóa</button></div></td></tr>)}</tbody></DataTable><Pagination page={safePage} pageSize={pageSize} total={filtered.length} onPageChange={setPage} onPageSizeChange={(size) => { setPageSize(size); setPage(0) }} /></StatePanel>
    {editorOpen && <Dialog title={editing ? `Sửa ${editing.stableId ?? editing.id}` : 'Tạo item'} onClose={closeEditor}><StatePanel query={skills}><form className="dialog-form" onSubmit={(event) => void submit(event)} key={editing?.id ?? 'new'}><Field label="Stable ID (tùy chọn)"><input name="stableId" defaultValue={editing?.stableId ?? ''} /></Field><Field label="Kỹ năng"><select name="skillId" required defaultValue={editing?.skillId ?? ''}><option value="" disabled>Chọn kỹ năng</option>{skills.data?.map((row) => <option value={row.id} key={row.id}>{row.code}</option>)}</select></Field><Field label="CEFR"><CefrSelect value={editing?.cefrLevel} /></Field><Field label="Loại"><select name="type" defaultValue={editing?.type ?? 'mcq'}>{['mcq','cloze','reorder','listening_mcq'].map((type) => <option key={type}>{type}</option>)}</select></Field><Field label="Câu hỏi"><textarea name="stem" required defaultValue={editing?.stem} /></Field><Field label="Lựa chọn (mỗi dòng)"><textarea name="options" defaultValue={editing?.options.join('\n')} /></Field><Field label="Đáp án"><input name="correctAnswer" required defaultValue={editing?.correctAnswer} /></Field><Field label="Giải thích"><textarea name="explanationVi" defaultValue={editing?.explanationVi ?? ''} /></Field><Field label="Nguồn"><input name="source" required defaultValue={editing?.source ?? 'Admin CMS'} /></Field><FormActions editing={Boolean(editing)} onCancel={closeEditor} /></form></StatePanel></Dialog>}
    {pendingDelete && <ConfirmDialog title="Xóa item" description={<>Xóa mềm item <code>{pendingDelete.stableId ?? pendingDelete.id}</code>?</>} confirmLabel="Xóa item" danger busy={deleting} onCancel={() => setPendingDelete(undefined)} onConfirm={() => void remove()} />}
    {generateOpen && <Dialog title="Tạo items bằng AI" onClose={closeGenerate}><p className="muted">Nội dung được tạo sẽ lưu trực tiếp vào ngân hàng item và có thể chỉnh sửa sau đó.</p><StatePanel query={skills}><form className="dialog-form" onSubmit={(event) => void generate(event)}><Field label="Kỹ năng"><select name="skillCode" required defaultValue=""><option value="" disabled>Chọn kỹ năng</option>{skills.data?.map((row) => <option value={row.code} key={row.id}>{row.code}</option>)}</select></Field><Field label="CEFR"><CefrSelect /></Field><Field label="Loại"><select name="type" defaultValue="mcq"><option value="mcq">mcq</option><option value="cloze">cloze</option></select></Field><Field label="Số lượng (1–20)"><input name="count" type="number" min="1" max="20" defaultValue="5" required /></Field>{generateError && <div className="state-card error" role="alert"><span>{generateError}</span></div>}<div className="form-actions dialog-actions"><button type="button" disabled={generating} onClick={closeGenerate}>Hủy</button><button className="primary" type="submit" disabled={generating}>{generating ? 'Đang tạo…' : 'Xác nhận tạo'}</button></div></form></StatePanel></Dialog>}
  </Page>
}
