import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { BookOpen, CheckCircle2, FileClock, ListChecks, Plus, Search } from 'lucide-react'
import { api, ApiError } from '../../../lib/api'
import type { Item, Lesson, Skill } from '../types'
import { CefrSelect, ConfirmDialog, DataTable, Dialog, Field, FormActions, Metric, OverflowText, Page, Pagination, StatePanel } from '../ui'
import { useQuery } from '../query'

const emptyLessons: Lesson[] = []

export function LessonsPanel(): ReactNode {
  const query = useQuery<Lesson[]>('/admin/lessons'); const skills = useQuery<Skill[]>('/admin/skills'); const items = useQuery<Item[]>('/admin/items'); const [editing, setEditing] = useState<Lesson>(); const [editorOpen, setEditorOpen] = useState(false); const [message, setMessage] = useState<string>(); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [skill, setSkill] = useState(''); const [page, setPage] = useState(0); const [pageSize, setPageSize] = useState(10); const [pendingDelete, setPendingDelete] = useState<Lesson>(); const [deleting, setDeleting] = useState(false)
  const lessons = query.data ?? emptyLessons
  const filtered = useMemo(() => lessons.filter((row) => { const keyword = search.trim().toLowerCase(); return (!keyword || `${row.title} ${row.titleVi} ${row.slug}`.toLowerCase().includes(keyword)) && (!status || (status === 'published') === row.isPublished) && (!skill || row.skillCode === skill) }), [lessons, search, skill, status]); const safePage = Math.min(page, Math.max(0, Math.ceil(filtered.length / pageSize) - 1)); const visibleLessons = filtered.slice(safePage * pageSize, (safePage + 1) * pageSize)
  useEffect(() => { if (safePage !== page) setPage(safePage) }, [page, safePage])
  const openCreate = (): void => { setEditing(undefined); setMessage(undefined); setEditorOpen(true) }
  const openEdit = (lesson: Lesson): void => { setEditing(lesson); setMessage(undefined); setEditorOpen(true) }
  const closeEditor = (): void => { setEditorOpen(false); setEditing(undefined) }
  const submit = async (event: FormEvent<HTMLFormElement>): Promise<void> => { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); const body = { stableId:String(values.get('stableId')), slug:String(values.get('slug')), title:String(values.get('title')), titleVi:String(values.get('titleVi')), descriptionVi:String(values.get('descriptionVi')), skillId:Number(values.get('skillId')), cefrLevel:String(values.get('cefrLevel')), order:Number(values.get('order')), isPublished:values.get('isPublished') === 'on', itemIds:String(values.get('itemIds')).split('\n').map((x) => x.trim()).filter(Boolean), source:editing ? editing.source : 'Admin CMS', license:editing ? editing.license : 'Proprietary', reviewer:editing ? editing.reviewer : 'Admin CMS', contentVersion:editing ? editing.contentVersion : 'admin-v1' }; try { await api(editing ? `/admin/lessons/${editing.id}` : '/admin/lessons', { method:editing ? 'PUT' : 'POST', body:JSON.stringify(body) }); closeEditor(); setMessage('Đã lưu bài học.'); await query.reload() } catch (reason) { setMessage(`Không thể lưu: ${reason instanceof ApiError ? reason.code : 'unexpected_error'}`) } }
  const remove = async (): Promise<void> => { if (!pendingDelete) return; setDeleting(true); try { await api(`/admin/lessons/${pendingDelete.id}`, { method:'DELETE' }); setPendingDelete(undefined); setMessage('Đã xóa bài học.'); await query.reload() } catch (reason) { setMessage(`Không thể xóa: ${reason instanceof ApiError ? reason.code : 'unexpected_error'}`); setPendingDelete(undefined) } finally { setDeleting(false) } }
  const published = lessons.filter((row) => row.isPublished).length
  return <Page title="Lesson Management" description="Quản lý catalog bài học, trạng thái publish và liên kết item." actions={<button className="primary" type="button" onClick={openCreate}><Plus size={18} aria-hidden="true" /> Tạo bài học</button>}>
    {message && <div className={`status-banner ${message.startsWith('Không thể') ? 'error' : ''}`} role="status">{message}</div>}
    <div className="metric-grid"><Metric label="Tổng bài học" value={lessons.length} icon={BookOpen} /><Metric label="Đã publish" value={published} hint="Sẵn sàng cho learner" icon={CheckCircle2} tone="success" /><Metric label="Bản nháp" value={lessons.length - published} hint="Chưa phát hành" icon={FileClock} tone="warning" /><Metric label="Item đã gán" value={lessons.reduce((sum, row) => sum + row.itemIds.length, 0)} hint="Tổng liên kết nội dung" icon={ListChecks} tone="neutral" /></div>
    <section className="card toolbar" aria-label="Bộ lọc bài học"><div className="toolbar-fields"><Field label="Tìm bài học"><div className="search-input"><Search aria-hidden="true" /><input type="search" value={search} onChange={(event) => { setSearch(event.target.value); setPage(0) }} placeholder="Tiêu đề hoặc slug…" /></div></Field><Field label="Trạng thái"><select value={status} onChange={(event) => { setStatus(event.target.value); setPage(0) }}><option value="">Tất cả</option><option value="published">Published</option><option value="draft">Draft</option></select></Field><Field label="Kỹ năng"><select value={skill} onChange={(event) => { setSkill(event.target.value); setPage(0) }}><option value="">Tất cả</option>{[...new Set(lessons.map((row) => row.skillCode))].sort().map((code) => <option key={code}>{code}</option>)}</select></Field></div><span className="toolbar-meta">{filtered.length} / {lessons.length} bài học</span></section>
    <StatePanel query={query}><DataTable empty={!filtered.length} stickyActions layout="lessons"><thead><tr><th>Thứ tự</th><th>Bài học</th><th>Kỹ năng</th><th>CEFR</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{visibleLessons.map((row) => <tr key={row.id}><td><span className="order-badge">{row.order}</span></td><td className="wide"><div className="lesson-cell"><span className="lesson-icon"><BookOpen aria-hidden="true" /></span><div><OverflowText text={row.titleVi} tone="primary" /><OverflowText text={`${row.slug} · ${row.itemIds.length} items`} tone="code" /></div></div></td><td><OverflowText text={row.skillCode} /></td><td><span className="badge">{row.cefrLevel}</span></td><td><span className={`badge ${row.isPublished ? 'live' : 'warning'}`}>{row.isPublished ? 'Published' : 'Draft'}</span></td><td><div className="table-actions"><button type="button" onClick={() => openEdit(row)}>Sửa</button><button className="danger" type="button" onClick={() => setPendingDelete(row)}>Xóa</button></div></td></tr>)}</tbody></DataTable><Pagination page={safePage} pageSize={pageSize} total={filtered.length} onPageChange={setPage} onPageSizeChange={(size) => { setPageSize(size); setPage(0) }} /></StatePanel>
    {editorOpen && <Dialog title={editing ? `Sửa ${editing.slug}` : 'Tạo bài học'} onClose={closeEditor}><StatePanel query={skills}><StatePanel query={items}><form className="dialog-form" onSubmit={(event) => void submit(event)} key={editing?.id ?? 'new'}><Field label="Stable ID"><input name="stableId" required defaultValue={editing?.stableId} /></Field><Field label="Slug"><input name="slug" required defaultValue={editing?.slug} /></Field><Field label="Tiêu đề"><input name="title" required defaultValue={editing?.title} /></Field><Field label="Tiêu đề Việt"><input name="titleVi" required defaultValue={editing?.titleVi} /></Field><Field label="Mô tả"><textarea name="descriptionVi" defaultValue={editing?.descriptionVi ?? ''} /></Field><Field label="Kỹ năng"><select name="skillId" required defaultValue={editing?.skillId ?? ''}><option value="" disabled>Chọn kỹ năng</option>{skills.data?.map((row) => <option value={row.id} key={row.id}>{row.code}</option>)}</select></Field><Field label="CEFR"><CefrSelect value={editing?.cefrLevel} /></Field><Field label="Thứ tự"><input name="order" type="number" required defaultValue={editing?.order ?? 1} /></Field><Field label="Item IDs (mỗi dòng)"><textarea name="itemIds" required defaultValue={editing?.itemIds.join('\n')} placeholder={items.data?.slice(0,2).map((item) => item.id).join('\n')} /></Field><label className="check"><input name="isPublished" type="checkbox" defaultChecked={editing?.isPublished} /> Published</label><FormActions editing={Boolean(editing)} onCancel={closeEditor} /></form></StatePanel></StatePanel></Dialog>}
    {pendingDelete && <ConfirmDialog title="Xóa bài học" description={<>Xóa mềm bài học <code>{pendingDelete.slug}</code>? Bài học sẽ được gỡ publish.</>} confirmLabel="Xóa bài học" danger busy={deleting} onCancel={() => setPendingDelete(undefined)} onConfirm={() => void remove()} />}
  </Page>
}
