import { useState, type ReactNode } from 'react'
import { Activity, Database, Eye, FileCheck2, Search, ShieldCheck, UploadCloud, Users } from 'lucide-react'
import { api, ApiError } from '../../../lib/api'
import type { AuditEvent, ImportPreview } from '../types'
import { ConfirmDialog, DataTable, Field, Metric, OverflowText, Page, Pagination, StatePanel } from '../ui'
import { useQuery } from '../query'

const importTemplate = JSON.stringify({ version:'2026.08.01-admin-v1', source:'LingoRoad Admin CMS', license:'Proprietary', reviewer:'Content reviewer', skills:[], items:[], lessons:[] }, null, 2)
export function ImportPanel(): ReactNode {
  const [payload, setPayload] = useState(importTemplate); const [preview, setPreview] = useState<{ value: ImportPreview; payload: string }>(); const [result, setResult] = useState<string>(); const [busy, setBusy] = useState(false); const [confirming, setConfirming] = useState(false); const [applied, setApplied] = useState(false)
  const validate = async (): Promise<void> => { setBusy(true); setResult(undefined); setPreview(undefined); setApplied(false); try { const body: unknown = JSON.parse(payload); const value = await api<ImportPreview>('/admin/imports/validate', { method:'POST', body:JSON.stringify(body) }); setPreview({ value, payload }); setResult(JSON.stringify(value,null,2)) } catch (reason) { setResult(`Lỗi: ${reason instanceof ApiError ? [reason.code,...reason.errors].join(', ') : reason instanceof Error ? reason.message : 'invalid_json'}`) } finally { setBusy(false) } }
  const apply = async (): Promise<void> => { if (!preview?.value.valid || preview.payload !== payload) return; setBusy(true); setConfirming(false); try { const body: unknown = JSON.parse(payload); const response = await api<unknown>('/admin/imports', { method:'POST', body:JSON.stringify(body) }); setResult(JSON.stringify(response,null,2)); setApplied(true); setPreview(undefined) } catch (reason) { setResult(`Lỗi: ${reason instanceof ApiError ? [reason.code,...reason.errors].join(', ') : 'invalid_json'}`) } finally { setBusy(false) } }
  const canApply = Boolean(preview?.value.valid && preview.payload === payload)
  return <Page title="Content Import" description="Validate, xem trước và áp dụng bundle nội dung bằng transaction idempotent.">
    <div className="stepper" aria-label="Tiến trình import"><div className={`step ${preview || applied ? 'complete' : 'active'}`}><span>1</span><strong>Validate</strong></div><div className={`step ${applied ? 'complete' : preview ? 'active' : ''}`}><span>2</span><strong>Preview</strong></div><div className={`step ${applied ? 'complete' : confirming ? 'active' : ''}`}><span>3</span><strong>Confirm</strong></div><div className={`step ${applied ? 'complete' : busy && canApply ? 'active' : ''}`}><span>4</span><strong>Apply</strong></div></div>
    {preview?.value.valid && <div className="metric-grid metric-grid-compact"><Metric label="Skills" value={preview.value.counts.skills} icon={ShieldCheck} /><Metric label="Items" value={preview.value.counts.items} icon={FileCheck2} tone="neutral" /><Metric label="Lessons" value={preview.value.counts.lessons} icon={Database} tone="success" /></div>}
    <section className="card import-card"><div className="section-heading"><div><h2>Content bundle JSON</h2><p>Mọi thay đổi payload đều yêu cầu validate lại.</p></div><UploadCloud aria-hidden="true" /></div><textarea aria-label="Content bundle JSON" value={payload} onChange={(event) => { setPayload(event.target.value); setPreview(undefined); setResult(undefined); setConfirming(false); setApplied(false) }} /><div className="form-actions"><button disabled={busy} type="button" onClick={() => void validate()}><Eye size={18} aria-hidden="true" /> Validate / Preview</button><button disabled={busy || !canApply} className="primary" type="button" onClick={() => setConfirming(true)}><UploadCloud size={18} aria-hidden="true" /> Apply</button></div>{result && <pre>{result}</pre>}</section>
    {confirming && preview && <ConfirmDialog title="Xác nhận import nội dung" description={<>Áp dụng bundle đã validate với checksum <code>{preview.value.checksum}</code>? Thao tác sẽ ghi dữ liệu thật.</>} confirmLabel="Xác nhận Apply" busy={busy} onCancel={() => setConfirming(false)} onConfirm={() => void apply()} />}
  </Page>
}

export function AuditPanel(): ReactNode {
  const query = useQuery<AuditEvent[]>('/admin/audit?limit=100'); const [search, setSearch] = useState(''); const [action, setAction] = useState(''); const [page, setPage] = useState(0)
  const rows = query.data ?? []; const filtered = rows.filter((row) => { const keyword = search.trim().toLowerCase(); return (!keyword || `${row.adminUserId} ${row.entityType} ${row.entityId} ${row.detail ?? ''}`.toLowerCase().includes(keyword)) && (!action || row.action === action) }); const pageSize = 20; const safePage = Math.min(page, Math.max(0, Math.ceil(filtered.length / pageSize) - 1)); const visibleRows = filtered.slice(safePage * pageSize, (safePage + 1) * pageSize)
  return <Page title="Audit Log" description="Theo dõi actor, hành động, entity và thời điểm của mọi mutation nội dung.">
    <div className="metric-grid metric-grid-compact"><Metric label="Sự kiện gần nhất" value={rows.length} icon={Activity} /><Metric label="Actors" value={new Set(rows.map((row) => row.adminUserId)).size} icon={Users} tone="neutral" /><Metric label="Loại entity" value={new Set(rows.map((row) => row.entityType)).size} icon={Database} tone="warning" /></div>
    <section className="card toolbar" aria-label="Bộ lọc audit"><div className="toolbar-fields"><Field label="Tìm trong audit"><div className="search-input"><Search aria-hidden="true" /><input type="search" value={search} onChange={(event) => { setSearch(event.target.value); setPage(0) }} placeholder="Actor, entity hoặc chi tiết…" /></div></Field><Field label="Hành động"><select value={action} onChange={(event) => { setAction(event.target.value); setPage(0) }}><option value="">Tất cả</option>{[...new Set(rows.map((row) => row.action))].sort().map((value) => <option key={value}>{value}</option>)}</select></Field></div><span className="toolbar-meta">{filtered.length} / {rows.length} sự kiện</span></section>
    <StatePanel query={query}><DataTable empty={!filtered.length} layout="audit"><thead><tr><th>Thời điểm</th><th>Actor</th><th>Hành động</th><th>Entity</th><th>ID</th><th>Chi tiết</th></tr></thead><tbody>{visibleRows.map((row) => <tr key={row.id}><td>{new Date(row.createdAt).toLocaleString('vi-VN')}</td><td><OverflowText text={row.adminUserId} tone="code" /></td><td><span className="badge">{row.action}</span></td><td><OverflowText text={row.entityType} /></td><td><OverflowText text={row.entityId} tone="code" /></td><td><OverflowText text={row.detail || '—'} lines={2} /></td></tr>)}</tbody></DataTable><Pagination page={safePage} pageSize={pageSize} total={filtered.length} onPageChange={setPage} /></StatePanel>
  </Page>
}
