import type { ReactNode } from 'react'
import { BarChart3, BookCheck, BookOpen, CircleCheck, ClipboardList, Clock3, MessageSquareText, Target, UserCheck, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { Analytics, AuditEvent } from '../types'
import { DataTable, Metric, Page, StatePanel } from '../ui'
import { useQuery } from '../query'

export function OverviewPanel(): ReactNode {
  const query = useQuery<Analytics>('/admin/analytics/overview'); const audit = useQuery<AuditEvent[]>('/admin/audit?limit=5'); const data = query.data
  return <Page title="Dashboard Overview" description="Theo dõi tổng quan nội dung và hoạt động học tập từ dữ liệu LingoRoad." actions={<Link className="button-link primary" to="/analytics"><BarChart3 size={18} aria-hidden="true" /> Xem báo cáo</Link>}><StatePanel query={query}>{data && <>
    <div className="metric-grid"><Metric label="Tổng người học" value={data.learners} hint="Tài khoản Learner" icon={Users} /><Metric label="Active 30 ngày" value={data.activeLearners} hint="Có hoạt động gần đây" icon={UserCheck} tone="success" /><Metric label="Bài hoàn thành" value={data.completedLessons} hint="Tổng lượt hoàn tất" icon={BookCheck} tone="neutral" /><Metric label="Độ chính xác" value={`${Math.round(data.correctness * 100)}%`} hint={`${data.answers} lượt trả lời`} icon={Target} tone="warning" /></div>
    <section><div className="section-heading"><div><h2>Tổng quan nội dung</h2><p>Cấu trúc học liệu đang được vận hành.</p></div></div><div className="metric-grid content-metrics"><Metric label="Kỹ năng" value={data.content.skills} icon={CircleCheck} /><Metric label="Bài học" value={data.content.lessons} icon={BookOpen} tone="neutral" /><Metric label="Đã publish" value={data.content.publishedLessons} icon={BookCheck} tone="success" /><Metric label="Items" value={data.content.items} icon={ClipboardList} tone="warning" /></div></section>
    <div className="overview-grid"><section className="card"><div className="section-heading"><div><h2>Mastery theo nhóm kỹ năng</h2><p>Khả năng trả lời đúng trung bình theo nhóm.</p></div></div><div className="progress-list">{data.mastery.length === 0 ? <p className="muted">Chưa có dữ liệu mastery.</p> : data.mastery.map((row) => <div className="progress-row" key={row.category}><span>{row.category}</span><progress aria-label={`Mastery ${row.category}`} value={row.average} max="1" /><strong>{Math.round(row.average * 100)}%</strong></div>)}</div></section>
      <section className="card"><div className="card-heading"><h2>Hoạt động gần đây</h2><Link to="/audit">Xem tất cả</Link></div><StatePanel query={audit}>{audit.data?.length ? <ul className="activity-list">{audit.data.map((row) => <li key={row.id}><span className="activity-dot" /><div><strong>{row.action} · {row.entityType}</strong><small>{row.adminUserId} · {new Date(row.createdAt).toLocaleString('vi-VN')}</small></div></li>)}</ul> : <p className="muted">Chưa có hoạt động.</p>}</StatePanel></section></div>
    <div className="overview-grid overview-bottom"><section className="card"><div className="section-heading"><div><h2>Items được sử dụng nhiều</h2><p>Ưu tiên rà soát các câu hỏi có lưu lượng cao.</p></div></div><DataTable empty={!data.itemUsage.length}><thead><tr><th>Item ID</th><th>Lượt làm</th><th>Độ chính xác</th></tr></thead><tbody>{data.itemUsage.slice(0,8).map((row) => <tr key={row.itemId}><td><code>{row.itemId}</code></td><td>{row.attempts}</td><td><span className={`badge ${row.correctness >= .7 ? 'live' : row.correctness < .5 ? 'error' : 'warning'}`}>{Math.round(row.correctness * 100)}%</span></td></tr>)}</tbody></DataTable></section><aside className="card insight-card"><Clock3 aria-hidden="true" /><h2>Nhịp học hiện tại</h2><p><strong>{data.dueReviews}</strong> thẻ đang đến hạn ôn tập trên toàn hệ thống.</p><div className="insight-stat"><MessageSquareText aria-hidden="true" /><span><strong>{data.answers}</strong><small>Lượt trả lời đã ghi nhận</small></span></div></aside></div>
  </>}</StatePanel></Page>
}
