import { useState, type FormEvent, type ReactNode } from 'react'
import { Boxes, GitBranch, Layers3, Plus, Search } from 'lucide-react'
import { api, ApiError } from '../../../lib/api'
import type { Skill } from '../types'
import { CefrSelect, ConfirmDialog, DataTable, Dialog, Field, FormActions, Metric, OverflowText, Page, Pagination, StatePanel } from '../ui'
import { useQuery } from '../query'

export function SkillsPanel(): ReactNode {
  const query = useQuery<Skill[]>('/admin/skills'); const [editing, setEditing] = useState<Skill>(); const [editorOpen, setEditorOpen] = useState(false); const [message, setMessage] = useState<string>(); const [search, setSearch] = useState(''); const [category, setCategory] = useState(''); const [page, setPage] = useState(0); const [pendingDelete, setPendingDelete] = useState<Skill>(); const [deleting, setDeleting] = useState(false)
  const rows = query.data ?? []; const filtered = rows.filter((row) => { const keyword = search.trim().toLowerCase(); return (!keyword || `${row.code} ${row.name} ${row.nameVi}`.toLowerCase().includes(keyword)) && (!category || row.category === category) }); const pageSize = 20; const safePage = Math.min(page, Math.max(0, Math.ceil(filtered.length / pageSize) - 1)); const visibleRows = filtered.slice(safePage * pageSize, (safePage + 1) * pageSize)
  const openCreate = (): void => { setEditing(undefined); setMessage(undefined); setEditorOpen(true) }; const openEdit = (row: Skill): void => { setEditing(row); setMessage(undefined); setEditorOpen(true) }; const closeEditor = (): void => { setEditorOpen(false); setEditing(undefined) }
  const submit = async (event: FormEvent<HTMLFormElement>): Promise<void> => { event.preventDefault(); setMessage(undefined); const values = new FormData(event.currentTarget); const parent = String(values.get('parentId') ?? ''); const body = { code:String(values.get('code')), name:String(values.get('name')), nameVi:String(values.get('nameVi')), category:String(values.get('category')), cefrLevel:String(values.get('cefrLevel')), parentId:parent ? Number(parent) : null }; try { await api(editing ? `/admin/skills/${editing.id}` : '/admin/skills', { method:editing ? 'PUT' : 'POST', body:JSON.stringify(body) }); closeEditor(); setMessage('Đã lưu kỹ năng.'); await query.reload() } catch (reason) { setMessage(`Không thể lưu: ${reason instanceof ApiError ? reason.code : 'unexpected_error'}`) } }
  const remove = async (): Promise<void> => { if (!pendingDelete) return; setDeleting(true); try { await api(`/admin/skills/${pendingDelete.id}`, { method:'DELETE' }); setPendingDelete(undefined); setMessage('Đã xóa kỹ năng.'); await query.reload() } catch (reason) { setMessage(`Không thể xóa: ${reason instanceof ApiError ? reason.code : 'unexpected_error'}`); setPendingDelete(undefined) } finally { setDeleting(false) } }
  return <Page title="Skill Taxonomy" description="Quản lý hệ thống kỹ năng, nhóm CEFR và quan hệ cha con." actions={<button className="primary" type="button" onClick={openCreate}><Plus size={18} aria-hidden="true" /> Tạo kỹ năng</button>}>
    {message && <div className={`status-banner ${message.startsWith('Không thể') ? 'error' : ''}`} role="status">{message}</div>}
    <div className="metric-grid metric-grid-compact"><Metric label="Tổng kỹ năng" value={rows.length} icon={Boxes} /><Metric label="Nhóm kỹ năng" value={new Set(rows.map((row) => row.category)).size} icon={Layers3} tone="neutral" /><Metric label="Kỹ năng gốc" value={rows.filter((row) => row.parentId === null).length} icon={GitBranch} tone="success" /></div>
    <section className="card toolbar" aria-label="Bộ lọc kỹ năng"><div className="toolbar-fields"><Field label="Tìm kỹ năng"><div className="search-input"><Search aria-hidden="true" /><input type="search" value={search} onChange={(event) => { setSearch(event.target.value); setPage(0) }} placeholder="Code hoặc tên…" /></div></Field><Field label="Nhóm"><select value={category} onChange={(event) => { setCategory(event.target.value); setPage(0) }}><option value="">Tất cả nhóm</option>{[...new Set(rows.map((row) => row.category))].sort().map((value) => <option key={value}>{value}</option>)}</select></Field></div><span className="toolbar-meta">{filtered.length} / {rows.length} kỹ năng</span></section>
    <StatePanel query={query}><DataTable empty={!filtered.length} stickyActions layout="skills"><thead><tr><th>Code</th><th>Tên kỹ năng</th><th>Nhóm</th><th>CEFR</th><th>Kỹ năng cha</th><th>Thao tác</th></tr></thead><tbody>{visibleRows.map((row) => <tr key={row.id}><td><OverflowText text={row.code} tone="code" /></td><td><OverflowText text={row.nameVi} tone="primary" /><OverflowText text={row.name} tone="secondary" /></td><td><span className="badge">{row.category}</span></td><td><span className="badge warning">{row.cefrLevel}</span></td><td><OverflowText text={rows.find((candidate) => candidate.id === row.parentId)?.code ?? '—'} /></td><td><div className="table-actions"><button type="button" onClick={() => openEdit(row)}>Sửa</button><button className="danger" type="button" onClick={() => setPendingDelete(row)}>Xóa</button></div></td></tr>)}</tbody></DataTable><Pagination page={safePage} pageSize={pageSize} total={filtered.length} onPageChange={setPage} /></StatePanel>
    {editorOpen && <Dialog title={editing ? `Sửa ${editing.code}` : 'Tạo kỹ năng'} onClose={closeEditor}><form className="dialog-form" onSubmit={(event) => void submit(event)} key={editing?.id ?? 'new'}><Field label="Code"><input name="code" required defaultValue={editing?.code} /></Field><Field label="Tên"><input name="name" required defaultValue={editing?.name} /></Field><Field label="Tên tiếng Việt"><input name="nameVi" required defaultValue={editing?.nameVi} /></Field><Field label="Nhóm"><input name="category" required defaultValue={editing?.category ?? 'grammar'} /></Field><Field label="CEFR"><CefrSelect value={editing?.cefrLevel} /></Field><Field label="Kỹ năng cha"><select name="parentId" defaultValue={editing?.parentId ?? ''}><option value="">Không có</option>{rows.filter((row) => row.id !== editing?.id).map((row) => <option value={row.id} key={row.id}>{row.code}</option>)}</select></Field><FormActions editing={Boolean(editing)} onCancel={closeEditor} /></form></Dialog>}
    {pendingDelete && <ConfirmDialog title="Xóa kỹ năng" description={<>Xóa mềm kỹ năng <code>{pendingDelete.code}</code>? Kỹ năng đang được tham chiếu sẽ bị server từ chối.</>} confirmLabel="Xóa kỹ năng" danger busy={deleting} onCancel={() => setPendingDelete(undefined)} onConfirm={() => void remove()} />}
  </Page>
}
