import { useEffect, useState, type ReactNode } from 'react'
import { BookCheck, ChevronLeft, CircleGauge, Clock3, Search, ShieldCheck, Target, UserCheck, Users } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import type { Analytics, AdminUser, UserDetail, UserListResponse } from '../types'
import { DataTable, Field, Metric, OverflowText, Page, StatePanel } from '../ui'
import { useQuery } from '../query'

const initials = (user: AdminUser): string => (user.name || user.email).split(/[\s@.]+/).filter(Boolean).slice(0,2).map((part) => part[0]?.toUpperCase()).join('')

export function UsersPanel(): ReactNode {
  const [search, setSearch] = useState(''); const [debounced, setDebounced] = useState(''); const [role, setRole] = useState(''); const [offset, setOffset] = useState(0)
  useEffect(() => { const timer = window.setTimeout(() => { setDebounced(search.trim()); setOffset(0) }, 300); return () => window.clearTimeout(timer) }, [search])
  const params = new URLSearchParams({ limit:'50', offset:String(offset) }); if (debounced) params.set('search', debounced); if (role) params.set('role', role)
  const query = useQuery<UserListResponse>(`/admin/users?${params}`)
  const allUsers = useQuery<UserListResponse>('/admin/users?limit=1&offset=0')
  const learners = useQuery<UserListResponse>('/admin/users?limit=1&offset=0&role=Learner')
  const admins = useQuery<UserListResponse>('/admin/users?limit=1&offset=0&role=Admin')
  const overview = useQuery<Analytics>('/admin/analytics/overview')
  return <Page title="User Management" description="Tra cứu tài khoản và theo dõi tiến độ học; dữ liệu chỉ đọc.">
    <div className="metric-grid"><Metric label="Tổng người dùng" value={allUsers.data?.total ?? '…'} hint="Mọi vai trò" icon={Users} /><Metric label="Active Learner" value={overview.data?.activeLearners ?? '…'} hint="Trong 30 ngày gần nhất" icon={UserCheck} tone="success" /><Metric label="Learner" value={learners.data?.total ?? '…'} hint="Tài khoản học tập" icon={CircleGauge} tone="neutral" /><Metric label="Admin" value={admins.data?.total ?? '…'} hint="Tài khoản quản trị" icon={ShieldCheck} tone="warning" /></div>
    <section className="card toolbar" aria-label="Bộ lọc người dùng"><div className="toolbar-fields"><Field label="Tìm người dùng"><div className="search-input"><Search aria-hidden="true" /><input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tên, email hoặc ID…" /></div></Field><Field label="Vai trò"><select value={role} onChange={(event) => { setRole(event.target.value); setOffset(0) }}><option value="">Tất cả vai trò</option><option value="Learner">Learner</option><option value="Admin">Admin</option></select></Field></div><span className="toolbar-meta">{query.data ? `Hiển thị ${query.data.users.length} / ${query.data.total}` : 'Đang tải…'}</span></section>
    <StatePanel query={query}><DataTable empty={!query.data?.users.length} stickyActions layout="users"><thead><tr><th>Người dùng</th><th>Vai trò</th><th>CEFR mục tiêu</th><th>Ngày tạo</th><th>Thao tác</th></tr></thead><tbody>{query.data?.users.map((row) => <tr key={row.id}><td><div className="user-cell"><span className="user-avatar">{initials(row)}</span><div><OverflowText text={row.name || 'Chưa đặt tên'} tone="primary" /><OverflowText text={row.email} tone="secondary" /></div></div></td><td><span className={`badge ${row.role === 'Admin' ? 'warning' : ''}`}>{row.role}</span></td><td>{row.targetCefr ?? '—'}</td><td>{new Date(row.createdAt).toLocaleDateString('vi-VN')}</td><td><div className="table-actions"><Link className="button-link" to={`/users/${row.id}`}>Xem chi tiết</Link></div></td></tr>)}</tbody></DataTable>{query.data && <div className="pagination"><span>{query.data.total === 0 ? '0' : `${offset + 1}–${Math.min(offset + 50, query.data.total)}`} / {query.data.total}</span><div><button type="button" disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 50))}>Trước</button><button type="button" disabled={offset + 50 >= query.data.total} onClick={() => setOffset(offset + 50)}>Sau</button></div></div>}</StatePanel>
  </Page>
}

export function UserDetailPanel(): ReactNode {
  const { id = '' } = useParams(); const query = useQuery<UserDetail>(`/admin/users/${id}`); const data = query.data
  if (query.error?.status === 404) return <Page title="Không tìm thấy người dùng" description="Tài khoản có thể đã bị xóa hoặc đường dẫn không còn hợp lệ." actions={<Link className="button-link" to="/users"><ChevronLeft size={18} aria-hidden="true" /> Danh sách người dùng</Link>}><div className="state-card error"><span>Không thể mở hồ sơ này.</span></div></Page>
  return <Page title={data?.name || 'Chi tiết người dùng'} description={data?.email ?? 'Đang tải hồ sơ và hoạt động học…'} actions={<Link className="button-link" to="/users"><ChevronLeft size={18} aria-hidden="true" /> Danh sách người dùng</Link>}><StatePanel query={query}>{data && <><div className="profile-hero card"><span className="profile-avatar">{initials(data)}</span><div><span className={`badge ${data.role === 'Admin' ? 'warning' : ''}`}>{data.role}</span><h2>{data.name || 'Chưa đặt tên'}</h2><p>{data.email}</p></div></div><div className="metric-grid user-metrics"><Metric label="Bài hoàn thành" value={data.activity.lessonsCompleted} icon={BookCheck} /><Metric label="Câu đã trả lời" value={data.activity.exercisesAnswered} icon={CircleGauge} tone="neutral" /><Metric label="Độ chính xác" value={data.activity.exercisesAnswered ? `${Math.round(data.activity.exercisesCorrect / data.activity.exercisesAnswered * 100)}%` : '—'} icon={Target} tone="success" /><Metric label="Thẻ cần ôn" value={data.activity.dueReviews} icon={Clock3} tone="warning" /></div><div className="overview-grid"><section className="card"><h2>Thông tin tài khoản</h2><dl className="details"><div><dt>Vai trò</dt><dd>{data.role}</dd></div><div><dt>CEFR mục tiêu</dt><dd>{data.targetCefr ?? '—'}</dd></div><div><dt>Ngày tạo</dt><dd>{new Date(data.createdAt).toLocaleString('vi-VN')}</dd></div><div><dt>Hoạt động gần nhất</dt><dd>{data.activity.lastActiveAt ? new Date(data.activity.lastActiveAt).toLocaleString('vi-VN') : 'Chưa có'}</dd></div></dl></section><section className="card"><h2>Mastery</h2><div className="progress-list">{data.mastery.length ? data.mastery.map((row) => <div className="progress-row" key={row.skillCode}><span>{row.skillName}</span><progress aria-label={`Mastery ${row.skillName}`} value={row.pCorrect} max="1" /><strong>{Math.round(row.pCorrect * 100)}%</strong></div>) : <p className="muted">Chưa có dữ liệu mastery.</p>}</div></section></div></>}</StatePanel></Page>
}
